# Generated by Django 4.2.2 on 2023-06-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multa', models.DecimalField(decimal_places=100, max_digits=100)),
                ('autor', models.CharField(max_length=100)),
                ('réu', models.CharField(max_length=100)),
                ('juiz', models.CharField(max_length=100)),
                ('recurso_especial', models.CharField(max_length=100)),
            ],
        ),
    ]
