# Generated by Django 4.2.2 on 2023-06-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OAB', models.IntegerField(max_length=23)),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=100)),
                ('telefone', models.IntegerField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
    ]
